---
- hosts: miners
  remote_user: ubuntu
  become: yes
  strategy: free

  vars_files:
    - vars/main.yml
    - vars/phala.yml

  roles:
    - precheck
    - hardware-info
    - defaults
    - sgx-install
    - sgx-test
    - docker

